---
- name: Fastest Mirror Tuning
  copy:
    dest: /etc/yum/pluginconf.d/fastestmirror.conf
    content: |
      [main]
      enabled=1
      verbose=0
      always_print_best_host = true
      socket_timeout=1
      #  Relative paths are relative to the cachedir (and so works for users as well
      # as root).
      hostfilepath=timedhosts.txt
      maxhostfileage=10
      maxthreads=500

- name: Wait for Centos to be accessible - eg just started containers networking can take a few seconds
  wait_for:
    host: mirrorlist.centos.org
    port: 80
    delay: 0
    sleep: 2
    timeout: 30
    state: started

- name: Yum Update
  command: yum -y update

- name: Basic packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - vim
      - wget
      - bash-completion
      - epel-release
      - sudo

- name: Bash Profile
  copy:
    src: ./../templates/etc/profile.d/zz_ec.sh
    dest: /etc/profile.d/zz_ec.sh

- name: Vim Config
  copy:
    src: ./../templates/etc/vimrc
    dest: /etc/vimrc

- name: Vim colour scheme
  copy:
    src: ./../templates/usr/share/vim/vimfiles/colors/deus.vim
    dest: /usr/share/vim/vimfiles/colors/deus.vim

- name: Locale
  copy:
    content: |
      LANG=en_GB.utf8
      export LANG
      LC_ALL=en_GB.UTF-8
      export LC_ALL
    dest: /etc/profile.d/zz_locale.sh

- name: Timezone
  command: timedatectl set-timezone Europe/London

- name: Passwordless Wheel Sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^.+?%wheel"
    line: "%wheel	ALL=(ALL)	NOPASSWD: ALL"
    validate: '/usr/sbin/visudo -cf %s'

- name: Set hostname to match ansible hostname
  command: hostnamectl set-hostname "{{ inventory_hostname }}"
