---
- name: Disable Yum Fastest Mirror
  replace:
    path: /etc/yum/pluginconf.d/fastestmirror.conf
    regexp: enabled=1
    replace: enabled=0

- name: Basic packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - vim
      - wget

- name: Bash Profile
  template:
    src: etc/profile.d/zz_ec.sh
    dest: /etc/profile.d/zz_ec.sh
